export const jobProgressPhrases = {
  justApplied: [
    "We received your submission for",
    "We are currently reviewing applications", 
    "A member of our Talent Acquisition team may contact you for more information if needed",
    "We've received your application for the", 
    "If we decide to move forward with your application",
    "are thrilled to receive your application", 
    "We will review submitted resumes", 
    "review your qualifications against the requirements", 
    "We will contact you soon should we feel that your background meets our current business needs.", 
    "received your information for", 
    "We received your application for",
    "Thank you for your application for",
    "We have received your information",
    "submitting your application",
    "Application successfully submitted",
    "We've received your resume",
    "Thanks for your application",
    "Your application is now under review",
    "We're reviewing your submission",
    "Application received and being processed",
    "We've got your details",
    "Thanks for applying",
    "Your information has been logged",
    "We're reviewing all submissions",
    "Application in our system",
    "Thank you for reaching out",
    "We'll be in touch shortly",
    "Your interest is appreciated",
    "Our team is reviewing applications",
    "We're assessing qualifications",
    "Review process has begun",
    "We're considering your profile",
    "Thanks for expressing interest",
    "Application under consideration",
    "We'll contact suitable candidates",
    "Your candidacy is noted",
    "Application details confirmed",
    "We're evaluating all applicants",
    "Your application is in queue",
    "Thank you for your submission",
    "We've added your application",
    "Review process underway",
    "We'll inform you of updates",
    "Expect to hear from us",
    "Your application is complete",
    "We value your interest",
    "Assessing your qualifications",
    "We're reviewing your credentials",
    "Application processing",
    "We've got your application",
    "Thanks for applying with us",
    "Your profile is being reviewed",
    "We'll be in touch soon",
    "We appreciate your patience",
    "Application now being reviewed",
    "We're evaluating all candidates",
    "Your application is active",
    "Thanks for sharing your resume",
    "We're considering your experience",
    "Application successfully logged",
    "We've noted your interest",
    "Reviewing submitted materials",
    "We'll reach out if a match",
    "Your application is under review"
  ],
  justRejected: [
    "While we were impressed with your qualifications", 
    "move forward with other candidates", 
    "encourage you to continue applying", 
    "opportunities that better align with your skills and experience", 
    "best of luck in your job search", 
    "unfortunately", 
    "against other current openings you may have applied to",
    "wish you the best with your job search", 
    "encourage you to visit our website to review future opportunities",
    "didn't work out this time", 
    "hope you will continue to explore other opportunities", 
    "wish you all the best in your search", 
    "we are moving forward with other candidates",
    "will not be able to move forward with your candidacy",
    "closed the job",
    "filled the job",
    "recruitment process for this role is being stopped",
    "has recently been filled",
    "not to move forward with your application",
     "Application not selected",
    "We're not moving forward",
    "We've filled the position",
    "Not selected for this role",
    "We've chosen another candidate",
    "Your application wasn't successful",
    "The position has been closed",
    "We wish you luck",
    "Consider other openings",
    "We're pursuing other candidates",
    "Not a match at this time",
    "Our needs have changed",
    "The role is no longer open",
    "Unsuccessful in this instance",
    "This opportunity is closed",
    "We've gone in another direction",
    "Best wishes in your search",
    "We encourage future applications",
    "Not advancing to the next stage",
    "We appreciate your understanding",
    "The search has concluded",
    "Thank you for your interest",
    "We wish you well",
    "Moving forward with others",
    "This application won't proceed",
    "Role has been finalized",
    "We're unable to proceed",
    "The position is no longer available",
    "Your application was declined",
    "Not the right fit now",
    "We've made our selection",
    "We wish you success",
    "This role has been filled",
    "Your qualifications weren't a match",
    "The recruitment process ended",
    "We've found our candidate",
    "We won't be moving forward",
    "you weren't selected",
    "you were not selected",
    "We've concluded our search",
    "Thank you for applying",
    "We're discontinuing your application",
    "This specific role is closed",
    "Best of luck with your career",
    "We're grateful for your interest",
    "Not a suitable candidate currently",
    "The hiring process is complete",
    "We appreciate your effort",
    "Not moving ahead with your profile",
    "This position is no longer active",
    "We've made a different choice",
    "filled the position",
    "not be extending an offer",
    "regret to inform you",
    "moved forward with candidates"
  ]
}

export const applicationPhrases = [
  // New Applications / Acknowledgements
  "Thank you for your application",
  "Application received",
  "Your application has been submitted",
  "Confirmation of application",
  "We've received your application",
  "Application Confirmation",
  "Regarding your recent application",
  "Candidate Application Update",
  "Your interest in", // Can be followed by company/role
  "Acknowledgement: Your Application for", // Can be followed by role
  "Welcome to our talent pool",
  "Next steps for your application",
  "We're reviewing your submission",

  // Interview Invitations
  "Interview Invitation",
  "Schedule your interview",
  "Interview with", // Can be followed by company/name
  "Next Steps: Interview for", // Can be followed by role
  "Virtual Interview Request",
  "Technical Interview Invitation",
  "Phone Interview Request",
  "Video Interview Invitation",
  "Invitation to Interview",
  "We'd like to schedule an interview",
  "Follow-up: Interview for", // Can be followed by role
  "Your Interview with", // Can be followed by interviewer name
  "Interview Confirmation",
  "Assessment Invitation",
  "On-site Interview",
  "Second Round Interview",
  "Final Interview",

  // Job Offers
  "Job Offer",
  "Offer of Employment",
  "Exciting Opportunity: ", // Can be followed by role/company
  "Employment Offer from", // Can be followed by company
  "Your Offer from", // Can be followed by company
  "Conditional Offer of Employment",
  "Offer Letter Enclosed",
  "Congratulations: Job Offer",
  "We'd like to offer you the position",
  "Official Job Offer",

  // Rejections / Unsuccessful Applications
  "Update on your application",
  "Regarding your application status",
  "Decision on your application",
  "Application Status Update",
  "Not moving forward",
  "Your application for", // Generic, common in rejections
  "Unsuccessful application",
  "Regarding your candidacy",
  "We regret to inform you",
  "Opportunity Update",
  "Next steps in the hiring process", // Can preface rejection
  "Thank you for your interest",
  "Our hiring team has made a decision",
  "We have decided to move forward with other candidates",
  "We will not be proceeding with your application",
  "Application closed",
  "Unfortunately, your application was not selected",
  "Candidate update",
  "Hiring decision for", // Can be followed by role

  // General / Ambiguous
  "Your application update",
  "Important update regarding your application",
  "Hiring Update",
  "Talent Acquisition",
  "A message from the HR team at",
  "Recruitment Update",

  // Body:
  "Thank you for applying to",
];

export const interviewPhrases = [
  "We would like to invite you for an interview",
  "We'd like to schedule an interview with you",
  "We were very impressed with your application and would like to learn more about your experience",
  "Your background and experience stood out",
  "We believe your qualifications align well with the requirements of the role",
  "To discuss your application further",
  "We'd be delighted to offer you an opportunity to interview",
  "Please select a time slot that works best for you",
  "We offer both in-person and virtual interview options",
  "Our hiring team is eager to speak with you",
  "The next step in our hiring process is an interview",
  "We are moving forward with your candidacy",
  "We would like to schedule a time to speak with you",
  "Could you please confirm your availability for an interview?",
  "We'd like to invite you to participate in an interview round",
  "We look forward to discussing this exciting opportunity with you",
  "Please follow the link below to book your interview",
  "You've been selected for an interview",
  "The interview process typically involves...",
  "We are very interested in learning more about your skills",
  "Invite you for an interview",
  "Schedule an interview",
  "Learn more about your experience",
  "Next step: interview",
  "Moving forward with your candidacy",
  "Select a time slot",
  "Eager to speak with you",
  "Book your interview",
  "You've been selected",
  "We'd like to meet"
]

export const offerPhrases = [
  "We are pleased to offer you the position of",
  "We would like to formally offer you the role of",
  "We are excited to extend an offer",
  "Your compensation package will include",
  "We are delighted to provide you with an offer of employment",
  "Your start date will be",
  "Please find attached your official offer letter",
  "We look forward to welcoming you to our team",
  "This offer outlines the terms and conditions of your employment",
  "Please review the attached offer letter carefully",
  "We believe you will be a valuable asset to our company",
  "Kindly sign and return this letter by",
  "Congratulations on your offer",
  "Your annual salary will be",
  "We're thrilled to have you join us",
  "Details regarding your benefits package are included",
  "Offer you the position",
  "Formally offer you the role",
  "Offer is contingent upon",
  "Extend an offer",
  "Compensation package includes",
  "Delighted to offer employment",
  "Your start date will be",
  "Attached your offer letter",
  "Welcome you to our team",
  "Outlines terms and conditions",
  "Review the attached offer",
  "Valuable asset to our company",
  "Sign and return by",
  "Congratulations on your offer",
  "Annual salary will be",
  "Thrilled to have you join",
  "Benefits package included",
  "offer you",
  "accept or decline this offer by"
]