export const jobProgressPhrases = {
  justApplied: [
    "We received your submission for",
    "We are currently reviewing applications", 
    "A member of our Talent Acquisition team may contact you for more information if needed",
    "We've received your application for the", 
    "If we decide to move forward with your application",
    "are thrilled to receive your application", 
    "We will review submitted resumes", 
    "review your qualifications against the requirements", 
    "We will contact you soon should we feel that your background meets our current business needs.", 
    "received your information for", 
    "We received your application for",
    "Thank you for your application for",
    "We have received your information",
  ],
  justRejected: [
    "While we were impressed with your qualifications", 
    "move forward with other candidates", 
    "encourage you to continue applying", 
    "opportunities that better align with your skills and experience", 
    "best of luck in your job search", 
    "unfortunately", 
    "against other current openings you may have applied to",
    "wish you the best with your job search", 
    "encourage you to visit our website to review future opportunities",
    "didn't work out this time", 
    "hope you will continue to explore other opportunities", 
    "wish you all the best in your search", 
    "we are moving forward with other candidates",
    "will not be able to move forward with your candidacy",
    "closed the job",
    "filled the job",
    "recruitment process for this role is being stopped",
    "has recently been filled",

  ]
}