export const jobProgressPhrases = {
  justApplied: [
    "confirm receipt of your application",
    "has been (?:\\w+\\s)?received",
    "We received your (?:\\w+\\s)?submission for",
    "We are (?:\\w+\\s)?currently (?:\\w+\\s)?reviewing applications",
    "A member of our Talent Acquisition team may contact you for more information if needed",
    "We've (?:\\w+\\s)?received your application for the",
    "If we decide to move (?:\\w+\\s)?forward with your application",
    "are (?:\\w+\\s)?thrilled to receive your application",
    "We will (?:\\w+\\s)?review (?:\\w+\\s)?submitted resumes",
    "review your qualifications against the requirements",
    "We will contact you (?:\\w+\\s)?soon should we feel that your background meets our current business needs.",
    "received your (?:\\w+\\s)?information for",
    "Thank you for your application",
    "Application (?:\\w+\\s)?successfully (?:\\w+\\s)?submitted",
    "We've received your resume",
    "Thanks for your application",
    "Your application is now (?:\\w+\\s)?under review",
    "We're (?:\\w+\\s)?reviewing your submission",
    "Application received and (?:\\w+\\s)?being processed",
    "We've got your (?:\\w+\\s)?details",
    "Thanks for applying",
    "Your information has been (?:\\w+\\s)?logged",
    "We're reviewing (?:\\w+\\s)?all submissions",
    "Application in our system",
    "Thank you for reaching out",
    "We'll be in touch (?:\\w+\\s)?shortly",
    "Your interest is (?:\\w+\\s)?appreciated",
    "Our team is (?:\\w+\\s)?reviewing applications",
    "We're (?:\\w+\\s)?assessing qualifications",
    "Review process has (?:\\w+\\s)?begun",
    "We're considering your profile",
    "Thanks for expressing interest",
    "Application (?:\\w+\\s)?under consideration",
    "We'll contact (?:\\w+\\s)?suitable candidates",
    "Your candidacy is (?:\\w+\\s)?noted",
    "Application (?:\\w+\\s)?details (?:\\w+\\s)?confirmed",
    "We're (?:\\w+\\s)?evaluating (?:\\w+\\s)?all applicants",
    "Your application is in queue",
    "Thank you for your submission",
    "We've added your application",
    "Review process (?:\\w+\\s)?underway",
    "We'll inform you of updates",
    "Expect to hear from us",
    "Your application is (?:\\w+\\s)?complete",
    "We value your interest",
    "Assessing your qualifications",
    "We're (?:\\w+\\s)?reviewing your credentials",
    "Application processing",
    "We've got your application",
    "Thanks for applying with us",
    "Your profile is (?:\\w+\\s)?being reviewed",
    "We'll be in touch (?:\\w+\\s)?soon",
    "We appreciate your patience",
    "Application now (?:\\w+\\s)?being reviewed",
    "We're (?:\\w+\\s)?evaluating (?:\\w+\\s)?all candidates",
    "Your application is (?:\\w+\\s)?active",
    "Thanks for sharing your resume",
    "We're considering your experience",
    "Application (?:\\w+\\s)?successfully logged",
    "We've noted your interest",
    "Reviewing (?:\\w+\\s)?submitted materials",
    "We'll reach out if a match",
    "is now (?:\\w+\\s)?under review",
  ],
  justRejected: [
    "While we were (?:\\w+\\s)?impressed with your qualifications",
    "move (?:\\w+\\s)?forward with (?:\\w+\\s)?other candidates[.!?;,]*",
    "encourage you to continue applying",
    "opportunities that (?:\\w+\\s)?better align with your skills and experience[.!?;,]*",
    "best of (?:\\w+\\s)?luck in your job search[.!?;,]*",
    "unfortunately",
    "against other (?:\\w+\\s)?current openings you may have applied to",
    "wish you the best with your job search[.!?;,]*",
    "encourage you to visit our website to review (?:\\w+\\s)?future opportunities[.!?;,]*",
    "didn't work out this time",
    "hope you will continue to explore (?:\\w+\\s)?other opportunities[.!?;,]*",
    "wish you (?:\\w+\\s)?all the best in your search[.!?;,]*",
    "we are moving (?:\\w+\\s)?forward with (?:\\w+\\s)?other candidates[.!?;,]*",
    "will not be able to move (?:\\w+\\s)?forward with your candidacy[.!?;,]*",
    "closed the job[.!?;,]*",
    "filled the job[.!?;,]*",
    "recruitment process for this role is (?:\\w+\\s)?being stopped[.!?;,]*",
    "has (?:\\w+\\s)?recently been filled[.!?;,]*",
    "not to move (?:\\w+\\s)?forward with your application[.!?;,]*",
    "Application not selected[.!?;,]*",
    "We're not moving (?:\\w+\\s)?forward[.!?;,]*",
    "We've filled the position[.!?;,]*",
    "Not selected for this role[.!?;,]*",
    "We've chosen (?:\\w+\\s)?another candidate[.!?;,]*",
    "Your application wasn't successful[.!?;,]*",
    "The position has been closed[.!?;,]*",
    "We wish you luck[.!?;,]*",
    "Consider (?:\\w+\\s)?other openings[.!?;,]*",
    "We're pursuing (?:\\w+\\s)?other candidates[.!?;,]*",
    "Not a match at this time[.!?;,]*",
    "Our needs have changed[.!?;,]*",
    "The role is no longer open[.!?;,]*",
    "Unsuccessful in this instance[.!?;,]*",
    "This opportunity is closed[.!?;,]*",
    "We've gone in (?:\\w+\\s)?another direction[.!?;,]*",
    "Best wishes in your search[.!?;,]*",
    "We encourage (?:\\w+\\s)?future applications[.!?;,]*",
    "Not advancing to the next stage[.!?;,]*",
    "We appreciate your understanding[.!?;,]*",
    "The search has (?:\\w+\\s)?concluded[.!?;,]*",
    "Thank you for your interest[.!?;,]*",
    "We wish you well[.!?;,]*",
    "Moving (?:\\w+\\s)?forward with others[.!?;,]*",
    "This application won't proceed[.!?;,]*",
    "Role has been (?:\\w+\\s)?finalized[.!?;,]*",
    "We're unable to proceed[.!?;,]*",
    "The position is no longer (?:\\w+\\s)?available[.!?;,]*",
    "Your application was declined[.!?;,]*",
    "Not the (?:\\w+\\s)?right fit now[.!?;,]*",
    "We've made our selection[.!?;,]*",
    "We wish you success[.!?;,]*",
    "This role has been filled[.!?;,]*",
    "Your qualifications weren't a match[.!?;,]*",
    "The recruitment process ended[.!?;,]*",
    "We've found our candidate[.!?;,]*",
    "We won't be moving (?:\\w+\\s)?forward[.!?;,]*",
    "you weren't selected[.!?;,]*",
    "you were not selected[.!?;,]*",
    "We've (?:\\w+\\s)?concluded our search[.!?;,]*",
    "Thank you for applying[.!?;,]*",
    "We're discontinuing your application[.!?;,]*",
    "This (?:\\w+\\s)?specific role is closed[.!?;,]*",
    "Best of luck with your career[.!?;,]*",
    "We're (?:\\w+\\s)?grateful for your interest[.!?;,]*",
    "Not a (?:\\w+\\s)?suitable candidate (?:\\w+\\s)?currently[.!?;,]*",
    "The hiring process is (?:\\w+\\s)?complete[.!?;,]*",
    "We appreciate your effort[.!?;,]*",
    "Not moving (?:\\w+\\s)?ahead with your profile[.!?;,]*",
    "This position is no longer (?:\\w+\\s)?active[.!?;,]*",
    "We've made a (?:\\w+\\s)?different choice[.!?;,]*",
    "not be extending an offer[.!?;,]*",
    "regret to inform you[.!?;,]*",
    "moved (?:\\w+\\s)?forward with candidates[.!?;,]*"
  ]
};

export const applicationPhrases = [
  // General applications:
  "application",
  // New Applications / Acknowledgements
  "Thank you for your application",
  "Application received",
  "Your application has been submitted",
  "Confirmation of application",
  "We've received your application",
  "Application Confirmation",
  "Regarding your (?:\\w+\\s)?recent application",
  "Candidate Application Update",
  "Your interest in", // Can be followed by company/role
  "Acknowledgement: Your Application for", // Can be followed by role
  "Welcome to our talent pool",
  "Next steps for your application",
  "We're reviewing your submission",

  // Interview Invitations
  "invite you for (?:\\w+\\s){0,4}interview(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*", // Matches "invite you for a virtual interview." or "invite you for an interview."
  "Schedule your interview", // Reverted to specific as a more general pattern might be too broad or complex for this simple phrase
  "Interview with", // Can be followed by company/name
  "Next Steps: Interview for", // Can be followed by role
  "Virtual Interview Request",
  "Technical Interview Invitation",
  "Phone Interview Request",
  "Video Interview Invitation",
  "Invitation to Interview",
  "We'd like to schedule an interview",
  "Follow-up: Interview for", // Can be followed by role
  "Your Interview with", // Can be followed by interviewer name
  "Interview Confirmation",
  "Assessment Invitation",
  "On-site Interview",
  "Second Round Interview",
  "Final Interview",

  // Job Offers
  "Job Offer",
  "Offer of Employment",
  "Exciting Opportunity: ", // Can be followed by role/company
  "Employment Offer from", // Can be followed by company
  "Your Offer from", // Can be followed by company
  "Conditional Offer of Employment",
  "Offer Letter Enclosed",
  "Congratulations: Job Offer",
  "We'd like to offer you the position",
  "Official Job Offer",

  // Rejections / Unsuccessful Applications
  "Update on your application",
  "Regarding your application status",
  "Decision on your application",
  "Application Status Update",
  "Not moving (?:\\w+\\s)?forward",
  "Your application for", // Generic, common in rejections
  "Unsuccessful application",
  "Regarding your candidacy",
  "We regret to inform you",
  "Opportunity Update",
  "Next steps in the hiring process", // Can preface rejection
  "Thank you for your interest",
  "Our hiring team has made a decision",
  "We have decided to move (?:\\w+\\s)?forward with (?:\\w+\\s)?other candidates",
  "We will not be proceeding with your application",
  "Application closed",
  "Unfortunately, your application was not selected",
  "Candidate update",
  "Hiring decision for", // Can be followed by role

  // General / Ambiguous
  "Your application update",
  "Important update regarding your application",
  "Hiring Update",
  "Talent Acquisition",
  "A message from the HR team at",
  "Recruitment Update",

  // Body:
  "Thank you for applying to",
];

export const interviewPhrases = [
  "invite you for (?:\\w+\\s){0,4}interview(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*", // Generalized, allowing 0-4 words before/after 'interview', ending with punctuation.
  "schedule your interview[.!?;,]*",
  "schedule an interview with you[.!?;,]*",
  "impressed with your application and would like to learn (?:\\w+\\s)?more about your experience[.!?;,]*",
  "Your background and experience stood out[.!?;,]*",
  "We believe your qualifications align (?:\\w+\\s)?well with the requirements of the role[.!?;,]*",
  "To discuss your application (?:\\w+\\s)?further[.!?;,]*",
  "We'd be (?:\\w+\\s)?delighted to offer you an opportunity to interview[.!?;,]*",
  "Please select a (?:\\w+\\s)?time slot that works (?:\\w+\\s)?best for you[.!?;,]*",
  "We offer both (?:\\w+\\s)?in-person and (?:\\w+\\s)?virtual interview options[.!?;,]*",
  "Our hiring team is (?:\\w+\\s)?eager to speak with you[.!?;,]*",
  "The next step in our hiring process is an interview[.!?;,]*",
  "We are moving (?:\\w+\\s)?forward with your candidacy[.!?;,]*",
  "We would like to schedule a time to speak with you[.!?;,]*",
  "Could you please confirm your availability for an interview?[.!?;,]*",
  "We'd like to invite you to participate in an interview round[.!?;,]*",
  "We look (?:\\w+\\s)?forward to discussing this (?:\\w+\\s)?exciting opportunity with you[.!?;,]*",
  "Please follow the link (?:\\w+\\s)?below to book your interview[.!?;,]*",
  "You've been selected for an interview[.!?;,]*",
  "The interview process typically involves(?:.*?)[.!?;]", // Matches until punctuation, for cases like "The interview process typically involves..."
  "We are (?:\\w+\\s)?very interested in learning (?:\\w+\\s)?more about your skills[.!?;,]*",
  "Next step: interview[.!?;,]*",
  "Book your interview[.!?;,]*",
  "We'd like to meet[.!?;,]*",
  "look (?:\\w+\\s)?forward to chatting with you[.!?;,]*"
];

export const offerPhrases = [
  "We are (?:\\w+\\s)?pleased to offer you the position of(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "We would like to (?:\\w+\\s)?formally offer you the role of(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "We are (?:\\w+\\s)?excited to extend an offer(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "Your compensation package will include(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "We are (?:\\w+\\s)?delighted to provide you with an offer of employment(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "Your start date will be(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "Please find attached your (?:\\w+\\s)?official offer letter(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "We look (?:\\w+\\s)?forward to (?:\\w+\\s)?welcoming you to our team(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "This offer outlines the terms and conditions of your employment(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "Please review the attached offer letter (?:\\w+\\s)?carefully(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "We believe you will be a (?:\\w+\\s)?valuable asset to our company(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "Kindly sign and return this letter by(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "Congratulations on your offer(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "Your annual salary will be(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "We're (?:\\w+\\s)?thrilled to have you join us(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "Details regarding your benefits package are included(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "Offer you the position(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "Formally offer you the role(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "Offer is contingent upon(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "Extend an offer(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "Compensation package includes(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "Delighted to offer employment(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "Attached your offer letter(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "Welcome you to our team(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "Outlines terms and conditions(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "Review the attached offer(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "Valuable asset to our company(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "Sign and return by(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "Annual salary will be(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "Thrilled to have you join(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "Benefits package included(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "offer you(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*",
  "accept or decline this offer by(?:\\s(?:\\w+\\s){0,4})?[.!?;,]*"
];